=== paullalonde/poco2swift/poco2swift/Configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Pod2SwiftConfiguration"
    targetNamespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd"
    elementFormDefault="qualified"
    xmlns="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:element name="poco2swift" type="Poco2SwiftType"/>
	
	<xs:complexType name="Poco2SwiftType">
		<xs:sequence>
			<xs:element name="imports" type="ImportsType" minOccurs="0"/>
			<xs:element name="skip-types" type="SkipsType" minOccurs="0"/>
			<xs:element name="external-types" type="ExternalsType" minOccurs="0"/>
			<xs:element name="enumerations" type="EnumerationsType" minOccurs="0"/>
			<xs:element name="classes" type="ClassesType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ImportsType">
		<xs:sequence>
			<xs:element name="module" type="ModuleType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExternalsType">
		<xs:sequence>
			<xs:element name="external-type" type="ExternalType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SkipsType">
		<xs:sequence>
			<xs:element name="skip-type" type="SkipType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ModuleType">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="ExternalType">
		<xs:attribute name="full-name" type="xs:string" use="required"/>
		<xs:attribute name="swift-name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="SkipType">
		<xs:attribute name="full-name" type="xs:string" use="optional"/>
		<xs:attribute name="match" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="EnumerationsType">
		<xs:sequence>
			<xs:element name="enum" type="EnumType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ClassesType">
		<xs:sequence>
			<xs:element name="class" type="ClassType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EnumType">
		<xs:complexContent>
			<xs:extension base="TypeType">
				<xs:sequence>
					<xs:element name="value" type="EnumValueType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ClassType">
		<xs:complexContent>
			<xs:extension base="TypeType">
				<xs:sequence>
					<xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TypeType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="include" type="xs:boolean" use="optional"/>
		<xs:attribute name="full-name" type="xs:string" use="optional"/>
		<xs:attribute name="swift-name" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="skip" type="xs:boolean" use="optional"/>
		<xs:attribute name="swift-name" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="EnumValueType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="skip" type="xs:boolean" use="optional"/>
		<xs:attribute name="swift-name" type="xs:string" use="optional"/>
	</xs:complexType>

</xs:schema>

=== paullalonde/poco2swift/poco2swift/Configuration.xml
<?xml version="1.0" encoding="utf-8" ?>
<poco2swift xmlns="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd" 
			   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			   xsi:schemaLocation="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd Configuration.xsd" >

	<imports>
		<module name="Foundation"/>
	</imports>

	<skip-types>
		<skip-type match="^SoftInfo\.Dme\.Model\.Search\.Drug\.Serialization\.Fav.+"/>
	</skip-types>

	<external-types>
		<external-type full-name="System.DateTime, mscorlib" swift-name="NSDate"/>
		<external-type full-name="System.DateTimeOffset, mscorlib" swift-name="NSDate"/>
		<external-type full-name="System.Decimal, mscorlib" swift-name="NSDecimalNumber"/>
		<external-type full-name="System.Guid, mscorlib" swift-name="NSUUID"/>
		<external-type full-name="System.TimeSpan, mscorlib" swift-name="NSTimeInterval" is-value-type="true"/>
		<external-type full-name="System.Uri, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" swift-name="NSURL"/>
		<external-type full-name="System.Version, mscorlib" swift-name="String" is-value-type="true"/>

		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.Clinical.ClinicalElementSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="ClinicalElementSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.Clinical.HistoricalElementSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="HistoricalElementSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.Clinical.HistoricalElementSummarySearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="HistoricalElementSummarySearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.HealthcareProviders.PharmacySearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="PharmacySearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.HealthcareProviders.PhysicianSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="PhysicianSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.HealthcareProviders.ServicePointPhysicianSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="ServicePointPhysicianSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.PatientIndex.PatientSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="PatientSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.PatientIndex.RamqRegistrationSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="RamqRegistrationSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.Security.RoleSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="RoleSearchResult"/>
		<external-type full-name="SoftInfo.Dme.ServicesDme.Common.Model.Security.UserSearchResult, SoftInfo.Dme.ServicesDme.Common.Model" swift-name="UserSearchResult"/>

		<!--<external-type full-name="SoftInfo.Dme.Model.Clinical.ClinicalElement, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.Clinical.HistoricalElement, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.HealthcareProviders.Pharmacy, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.HealthcareProviders.Physician, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.HealthcareProviders.ServicePointPhysician, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.PatientIndex.Patient, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.Ramq.RamqRegistration, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.Security.FullRole, SoftInfo.Dme.Model" swift-name="Bool"/>
		<external-type full-name="SoftInfo.Dme.Model.Security.User, SoftInfo.Dme.Model" swift-name="Bool"/>-->
	</external-types>
	
	<enumerations>
		
		<!--<enum full-name="SoftInfo.Dme.Model.Security.Rbac.ScalarAttributeType, SoftInfo.Dme.Model">
			<value name="Unknown" swift-name="UnknownType"/>
			<value name="String" swift-name="StringType"/>
			<value name="Int32" swift-name="Int32Type"/>
			<value name="DateTime" swift-name="DateTimeType"/>
			<value name="LicensingBody" swift-name="LicensingBodyType"/>
			<value name="PersonGender" swift-name="PersonGenderType"/>
			<value name="Province" swift-name="ProvinceType"/>
		</enum>-->
		
		<enum full-name="SoftInfo.Dme.Model.Clinical.AbnormalFlagNature, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.AcknowledgementDetailType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ActDetectedIssueCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ActMedicationTherapyDurationWorkingListCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ActObservationHeightOrWeight, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ActPharmacySupplyType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.ActPriority, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ActStatus, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.ActUncertainty, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.AddressClass, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.AdministrableDrugForm, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.AdministrationSiteCodeSystem, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.AdministrativeContactRoleType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Appointments.AppointmentState, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicAddressPartType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicPersonNamePartQualifier, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicPersonNamePartType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicPersonNameUse, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicPostalAddressUse, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.BasicTelecommunicationAddressUse, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.BillableActCodeSystem, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Care.CareElementComparisonOperator, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Care.CareElementDataType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Care.CareElementLocation, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Care.CareValueStatus, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ClinicalDeviceEntity, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.ClinicalDrug, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.ClinicalElementType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.Country, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.DiagnosticCodeSystemIdentifier, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.DosageFrequency, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.DrugFormCodeSystem, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.DrugRouteCodeSystem, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.DrugUnitOfMeasure, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Configuration.DsqEnvironment, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Dsq.DsqSynchronizationResultType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.EmailClass, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Care.ExposureElementDataType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.FamilyRelation, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Drug.HeightOrWeightObservationUnitOfMeasure, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.HealthcareProviders.IdentifiedLocationScope, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.ImagingProcessStepCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.IntoleranceValue, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.LabReportStatusCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.LabRequestProcessStepCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.LabResultObservationValueType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.LabResultProcessStepCode, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.Language, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.HealthcareProviders.LicensingBody, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.LifeStage, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.LoincScaleType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.MedicalSpecialtyCodeSystem, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Reference.NonDrugAgentEntityClass, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Customization.NoteTemplateItemSize, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Customization.NoteTemplateItemType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.ObservationInterpretation, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.PatientIndex.PatientRelation, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.PatientIndex.PatientStatusInClinic, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Clinical.PersonalHistoryType, SoftInfo.Dme.Model"/>
		<enum full-name="SoftInfo.Dme.Model.Contacts.PersonGender, SoftInfo.Dme.Model"/>
